### PR TITLE
Code coverage support

### PR DESCRIPTION
**Pull request by abtris**

### CODE REVIEW

**Comment by Almad** [comment]
@abtris it might be worth settling on the same set of technologies ;)

Please reach out to @netmilk , also see https://github.com/apiaryio/fury/pull/1

**Comment by abtris** [comment]
I think this solution is simpler than apiaryio/fury#1

**Comment by netmilk** [comment]
@abtris good to know that `istanbul` now supports instrumenting both coffee & js. 

It's worth adding [coveralls](https://coveralls.io/) reporting as well. It points out coverage trend between commits.

**Comment by Almad** [comment]
@netmilk is there a way to do that without the comment spam?

**Comment by netmilk** [comment]
Yes it is.
screen shot 2015-02-19 at 18 51 26

**Comment by jsarenik** [comment]
Merging. :+1:

**Pull request merged**
